### ISSUE TITLE
LLM Connection

### ISSUE THREAD

**Issue by meric2** [emre-bl/EVI-AI#4]
LLM API should be connected and the ouputs should be redirected for this specific problem. 
For now there are scripts written by @mericdemirors to reach the API and run it on the local machine. The scripts will be organized again to serve the purpose explained above. Then the output will be sent to server to mobile app for further usage.

**Comment by emre-bl** [comment]
![image](https://github.com/emre-bl/EVI-AI/assets/57074947/5d9f37f0-18b9-47e1-b500-05fa39478179)

Bu kısım doldurulacak. (pipeline_scripts/server.py)
